# Generated by Django 4.2.5 on 2023-10-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
